using Denomica.OpenAI.Extensions.Model;
using System;
using System.Collections.Generic;
using System.Text;

namespace Denomica.OpenAI.Extensions.Embeddings
{
    /// <summary>
    /// Represents the response containing an embedding vector generated by a model.
    /// </summary>
    /// <remarks>The <see cref="Vector"/> property provides the embedding vector, which is typically used
    /// for tasks such as similarity comparisons, clustering, or other machine learning applications. The vector is
    /// generated by the model and may vary in length depending on the model's configuration.</remarks>
    public class EmbeddingResponse : ModelResponse
    {
        /// <summary>
        /// Gets or sets the embedding vector represented as an array of floating-point values.
        /// </summary>
        public float[] Vector { get; set; } = new float[0];
    }
}
